-- VeryReport Developer Hub — Oracle demo (adjust schema/user as needed)
-- See: examples/oracle/README.md

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE vr_demo_sales';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE vr_demo_sales (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  biz_date      DATE           NOT NULL,
  region        VARCHAR2(32)   NOT NULL,
  product_line  VARCHAR2(64)   NOT NULL,
  amount        NUMBER(18, 2)  NOT NULL,
  qty           NUMBER(10)     NOT NULL
);

CREATE INDEX idx_vr_demo_sales_date ON vr_demo_sales (biz_date);

INSERT INTO vr_demo_sales (biz_date, region, product_line, amount, qty) VALUES
  (DATE '2026-01-05', '华东', '标准版', 12800, 4);
INSERT INTO vr_demo_sales (biz_date, region, product_line, amount, qty) VALUES
  (DATE '2026-01-08', '华东', '专业版', 25600, 2);
INSERT INTO vr_demo_sales (biz_date, region, product_line, amount, qty) VALUES
  (DATE '2026-01-12', '华南', '标准版', 9600, 3);
INSERT INTO vr_demo_sales (biz_date, region, product_line, amount, qty) VALUES
  (DATE '2026-01-15', '华南', '专业版', 38400, 3);
INSERT INTO vr_demo_sales (biz_date, region, product_line, amount, qty) VALUES
  (DATE '2026-01-18', '华北', '标准版', 11200, 4);
INSERT INTO vr_demo_sales (biz_date, region, product_line, amount, qty) VALUES
  (DATE '2026-02-03', '华东', '旗舰版', 48000, 1);
INSERT INTO vr_demo_sales (biz_date, region, product_line, amount, qty) VALUES
  (DATE '2026-02-11', '西南', '专业版', 19200, 2);
INSERT INTO vr_demo_sales (biz_date, region, product_line, amount, qty) VALUES
  (DATE '2026-02-18', '华南', '旗舰版', 56000, 1);

COMMIT;
